### ISSUE TITLE
当层级大于等于3的时候，使用expandAllParents()方法会出现数据错位

### ISSUE THREAD

**Issue by jas0nchen** [zaihuishou/ExpandableRecyclerview#16]
如题，我目前根据自己的需求简单修改了一下，只适配了3层的情况，修改的是BaseExpandableAdapter下的expandParentListItem()方法。具体如下，适配更高层级的还要等作者下次修复喽~

/**
     * expand index item (Fixed by Jason. now it just adjust triple level, no more level!!!!!!!)
     *
     * @param expandableListItem
     * @param parentIndex                       The index of the parent to collapse
     * @param expansionTriggeredByListItemClick
     */
    protected void expandParentListItem(ExpandableListItem expandableListItem, int parentIndex, boolean expansionTriggeredByListItemClick, boolean isExpandAllChildren) {
        if (!expandableListItem.isExpanded()) {
            List<?> childItemList = expandableListItem.getChildItemList();
            if (childItemList != null && !childItemList.isEmpty()) {
                expandableListItem.setExpanded(true);
                int childListItemCount = childItemList.size();
                for (int i = 0; i < childListItemCount; i++) {
                    Object o = childItemList.get(i);
                    int newIndex = parentIndex + i + 1;
                    **if (isExpandAllChildren && i > 0) {
                        for(int j = 0; j < i; j++){
                            Object childBefore = childItemList.get(j);
                            if(childBefore instanceof ExpandableListItem){
                                newIndex += ((ExpandableListItem) childBefore).getChildItemList().size();
                            }
                        }
                    }**
                    mDataList.add(newIndex, o);
                    notifyItemInserted(newIndex);
                    if (isExpandAllChildren)
                        if (o instanceof ExpandableListItem) {
//                            notifyItemInserted(newIndex);
//                            if (parentIndex != mDataList.size() - 1)
//                                notifyItemRangeChanged(parentIndex + 1, mDataList.size() - parentIndex - 1);
                            expandParentListItem((ExpandableListItem) o, newIndex, expansionTriggeredByListItemClick, isExpandAllChildren);
                        }
                }
//                notifyItemRangeInserted(parentIndex + 1, childListItemCount);
                int positionStart = parentIndex + childListItemCount;
                if (parentIndex != mDataList.size() - 1)
                    notifyItemRangeChanged(positionStart, mDataList.size() - positionStart);

//                notifyItemExpandedOrCollapsed(parentIndex, true);
            }
            if (expansionTriggeredByListItemClick && mExpandCollapseListener != null) {
                int expandedCountBeforePosition = getExpandedItemCount(parentIndex);
                mExpandCollapseListener.onListItemExpanded(parentIndex - expandedCountBeforePosition);
            }
        }
    }

**Comment by zaihuishou** [comment]
感谢你的issue.
你如果测试没问题可以给我个pull request.
