### ISSUE TITLE
Collapse other then current expanded?

### ISSUE THREAD

**Issue by chiragdigi** [zaihuishou/ExpandableRecyclerview#2]
How to collapse all and collapse other then expanded current parent item?

**Comment by zaihuishou** [comment]
Please wait a moment, I'll add the next version

**Comment by s13524801** [comment]
Actually, bignerdranch/expandable-recycler-view is easy to use. You don't have to cut it.

**Comment by zaihuishou** [comment]
@s13524801  it support three and more?

**Comment by progratient** [comment]
@chiragdigi  hi,there, you can check my implemented lib, welcome  pull request ,issues ,thanks!
https://github.com/HuaJianJiang/ExpandableRecyclerView
