### ISSUE TITLE
展开关闭有问题

### ISSUE THREAD

**Issue by wenchyron** [zaihuishou/ExpandableRecyclerview#20]
@Override
    public void onParentListItemCollapsed(int position) {
        Object o = mDataList.get(position);
        if (o instanceof ExpandableListItem) {
            collapseParentListItem((ExpandableListItem) o, position, true);
        }
    }

    /**
     * expand parent item
     *
     * @param position The index of the item in the list being expanded
     */
    @Override
    public void onParentListItemExpanded(int position) {
        try {
            Object o = mDataList.get(position);
            if (o instanceof ExpandableListItem) {
                expandParentListItem((ExpandableListItem) o, position, true, false);
            }
        } catch (IndexOutOfBoundsException e) {
        }
    }

展开有几率会展不开要点其他item在点出问题展不开的这个item才能恢复
关闭有几率会导致程序崩溃 

怎么解决呢

**Comment by zaihuishou** [comment]
具体是在做什么操作的时候？

**Comment by wenchyron** [comment]
就是点击展开有几率，子项展不开

/**
 * expand parent item
 *
 * @param position The index of the item in the list being expanded
 */
@Override
public void onParentListItemExpanded(int position) {
    try {
        Object o = mDataList.get(position);
        if (o instanceof ExpandableListItem) {
            expandParentListItem((ExpandableListItem) o, position, true, false);
        }
    } catch (IndexOutOfBoundsException e) {
    }
}

应该是这里出的问题 IndexOutOfBoundsException  
关闭 子项的时候也有几率会出问题，因为onParentListItemCollapsed这个方法里没有try catch 会直接崩溃掉

**Comment by zaihuishou** [comment]
推荐你用airbnb开源的[Epoxy](https://github.com/airbnb/epoxy)代替
