### ISSUE TITLE
adapter.notifyItemChanged(pos, item) not working

### ISSUE THREAD

**Issue by Skullper** [zaihuishou/ExpandableRecyclerview#28]
I'm trying to update views but only parent items got updates. Children stay not updated. Example:
if I have Parent with one child. Then I have add one more child and update parent by running `notifyItemChanged(parentPosition, parentObject)`. I saw the same list. 
`modifyItem()` not working too.
How to fix this?

**Comment by zaihuishou** [comment]
You can use [Epoxy](https://github.com/airbnb/epoxy)
