### ISSUE TITLE
OnClickListener for child item

### ISSUE THREAD

**Issue by nevi-me** [zaihuishou/ExpandableRecyclerview#3]
Hey, great library! Was trying it out, but I can't seem to set an OnClick listener other than on an `AbstractAdapterItem`. How can I do that inside my recycler or the base adapter?

**Comment by nevi-me** [comment]
I sort of found a place to hook a listener, on `onUpdateViews` of an `AbstractAdapterItem`, but I had to make my classes inner classes so I could access the application context.

A more elegant solution would be better, though I think I'm missing something that you've done.

**Comment by zaihuishou** [comment]
You can set set an OnClick listener at AbstractAdapterItem **onBindViews(final View root)**.The purpose of this library is to make a different type of item can be really different listener,so can not set only one listener to deal with all item click operation.

**Comment by nevi-me** [comment]
Thanks, I had tried it there but it didn't work. I'm using onUpdateView.

Thanks again for working in the library, saved me a weekend!
