### ISSUE TITLE
请问：怎么添加单击事件

### ISSUE THREAD

**Issue by xuanu** [zaihuishou/ExpandableRecyclerview#6]
EmployeeItem  extends  AbstractAdapterItem.onBindViews(root){
 root.setOnClickListener(this);
}
添加单击事件没有效果。
单击的时候怎么带数据？

**Comment by xuanu** [comment]
点击事件好像有效果了，想问下怎么获得当前点击位置的数据。

**Comment by zaihuishou** [comment]
@xuanu 可以在AbstractExpandableAdapterItem 中onBindViews方法添加点击事件控制item展开或者收起。获取点击位置的数据可以看最新demo。
