### ISSUE TITLE
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by qq897425998** [zaihuishou/ExpandableRecyclerview#7]
when I import project I get this error
导入时报错

**Comment by SubhrajyotiSen** [comment]
This is mostly an issue with your gradle confirguration. Can you please recheck your compileSDK and buildTools version

**Comment by zaihuishou** [comment]
@qq897425998 请问具体是什么错？

**Comment by zaihuishou** [comment]
@SubhrajyotiSen First of all, thank you for your pull request.I have rechecked my gradle confirguration,but i have not found issues.Please tell me the specific question.

**Comment by SubhrajyotiSen** [comment]
My post was for @qq897425998 since the error that he mentioned is mostly related to his gradle configuration

**Comment by progratient** [comment]
@qq897425998 可以看下我的实现，欢迎 pull request，issues，fork
https://github.com/HuaJianJiang/ExpandableRecyclerView
