### ISSUE TITLE
能添加固定 head 么

### ISSUE THREAD

**Issue by xiaomsh** [zaihuishou/ExpandableRecyclerview#9]
能加个功能吗？上下移动的时候，表头可见，固定在 item 上方，比如你的 Department 上下滑动，该 Department 上的 Google 就悬浮在上面，而不是随着 item 一起消失

**Comment by zaihuishou** [comment]
@wenchaosong 设置全部展开调用BaseExpandableAdapter collapseAllParents方法。
 在onExpandsionToggled方法中你可以设置动画，或者不设。

**Comment by xiaomsh** [comment]
全部展开我刚才已经弄了，mBaseExpandableAdapter.expandAllParents();  调用这个就行

**Comment by zaihuishou** [comment]
@wenchaosong 关于parent item 悬停的功能可以自己实现，目前这个功能不准备加入。

**Comment by xiaomsh** [comment]
@zaihuishou 好吧，现在我是时间比较紧，能给点建议怎么实现么

**Comment by zaihuishou** [comment]
@wenchaosong 你可以监听Recyclerview的ScrollListener，在这里面去实现让item悬停的功能

**Comment by xiaomsh** [comment]
@zaihuishou 好的，谢谢。最后一个问题，在这些上面加一个 head ，比如在 Google 上面加个 head 布局，有现成的方法添加么，还是只能继承 AbstractAdapterItem 然后自己写？
我现在的需求是，在上面添加一个横向的 RecyclerView ，要实现的话是继承 AbstractAdapterItem ，然后子 item 也是继承这个么

**Comment by zaihuishou** [comment]
@wenchaosong  对，你可以继承AbstractAdapterItem，然后写你的header布局

**Comment by xiaomsh** [comment]
@zaihuishou 好的，谢谢

**Comment by zaihuishou** [comment]
@wenchaosong 不用谢。
